name: "Frontend - Deploy Micro-Applications"

on:
  workflow_run:
    workflows: ["Frontend - Build and Archive Micro-Applications"]
    types: [completed]
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Choose the version"
        required: true
        default: "dev"
      instance:
        type: choice
        description: "Choose the instance"
        required: true
        default: "dev"
        options:
          - dev
          - ua
          - preprod
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  getting-applications-zips:
    environment: dev
    name: Resolve inputs and list Micro-Applications
    if: ${{ github.event_name == 'workflow_dispatch' || ( github.event.workflow_run.conclusion == 'success' && !(github.event.workflow_run.event == 'push' && startsWith(github.event.workflow_run.head_branch, 'hotfix'))) }}
    outputs:
      instance: ${{ steps.resolve.outputs.instance }}
      version: ${{ steps.resolve.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Resolve version and instance inputs
        id: resolve
        shell: bash
        run: |
          EVENT="${{ github.event.workflow_run.event }}"
          BRANCH="${{ github.ref_name }}"
          TAG="${{ github.event.workflow_run.head_branch }}"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
            echo "instance=${{ inputs.instance }}" >> $GITHUB_OUTPUT
          elif [[ "$EVENT" == "pull_request" ]]; then
            echo "version=dev" >> $GITHUB_OUTPUT
            echo "instance=dev" >> $GITHUB_OUTPUT
          else
              echo "version=$TAG" >> $GITHUB_OUTPUT
              echo "instance=ua" >> $GITHUB_OUTPUT
          fi

      - name: Assuming federated role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Pulumi-Role

          
      - name: Check version existence
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          if aws s3 ls "s3://${{ secrets.ARCHIVE_BUCKET_NAME }}/frontend/${{ steps.resolve.outputs.version }}/" > /dev/null 2>&1; then
            echo "::notice::Version exists."
          else
            echo "::error::Wrong version number: ${{ steps.resolve.outputs.version }}"
            exit 1
          fi

      - run: |
          mkdir apps

      - name: Download application archive from S3
        run: aws s3 cp s3://${{ secrets.ARCHIVE_BUCKET_NAME }}/frontend/${{ steps.resolve.outputs.version }}/ ./apps/ --recursive

      - name: Add Frontend Infrastruture to artifact directory
        run: |
          cp -r ./deployments/frontend ./apps/ 

      - name: Upload applications archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: All-Apps
          path: ./apps/

      - name: Post text to a Slack channel
        if: failure()               
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.DEVOPS_SLACK_ID }}
            text: |
              ❌ Frontend Deployment Workflow failed
              Workflow: ${{ github.workflow }}
              Repo: ${{ github.repository }}
              Actor: ${{ github.actor }}
              Environment: ${{ steps.resolve.outputs.version }}
  deploy-application:
    name: Deploy application
    needs: getting-applications-zips
    environment: ${{ needs.getting-applications-zips.outputs.instance }}
    runs-on: ubuntu-latest
    steps:
      - name: Assume main role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Federal

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        

      - name: Chain deploy role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_WORKER_ROLE_ARN }}
          role-session-name: Secondary
          role-chaining: true
      
      - run: |
          mkdir apps

      - name: Download applications archive from artifact
        uses: actions/download-artifact@v7
        with:
          name: All-Apps
          path: ./apps/

      - name: Unzip apps and config bootstrapjs
        run: |
          cd apps
          for file in *.zip; do
            name="${file%.zip}"     
            mkdir -p "$name"
            unzip "$file" -d "$name"
            cd $name
            ./bootstrapjs.sh >> bootstrap.js
            rm bootstrapjs.sh
            cd ..
            
          done
          rm *.zip
          mv frontend ..


      - name: Terraform Init (with backend config)
        run: |
          cd frontend
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=frontend-${{ needs.getting-applications-zips.outputs.instance }}/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Terraform Apply
        run: |
          cd frontend
          terraform apply -auto-approve  
        env:
          TF_VAR_aws_region: ${{ vars.AWS_REGION }}
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
          TF_VAR_environment: ${{ needs.getting-applications-zips.outputs.instance }}
          TF_VAR_node_version: 22


      - name: Post text to a Slack channel
        if: failure()               
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.DEVOPS_SLACK_ID }}
            text: |
              ❌ Frontend Deployment Workflow failed
              Workflow: ${{ github.workflow }}
              Repo: ${{ github.repository }}
              Actor: ${{ github.actor }}
              Environment: ${{ needs.getting-applications-zips.outputs.instance }}