name: Check app PnPm packages for vulnerabilities

on: 
  pull_request:
    types:
      - ready_for_review

permissions:
  id-token: write
  contents: read
env:
  NODE_VERSION: 20
  PNPM_VERSION: 10

jobs:
  vulnerabilities-scan:
    environment: dev
    name: Vulnerabilities Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/forntend/code/
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

       
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: code/forntend/code/pnpm-lock.yaml



      - name: Downloading PNPM dependencies and auditing
        run: |
            WARNING_LINE=$(pnpm install | grep "vulnerabilities" || true)

            pnpm audit --json > audit_results.json || true

            echo "Full pnpm audit output:"
            cat audit_results.json

            HIGH_SEVERITY=$(jq '.metadata.vulnerabilities.high // 0' audit_results.json)
            CRITICAL_SEVERITY=$(jq '.metadata.vulnerabilities.critical // 0' audit_results.json)

            echo "High vulnerabilities: $HIGH_SEVERITY"
            echo "Critical vulnerabilities: $CRITICAL_SEVERITY"

            if [ "$HIGH_SEVERITY" -gt 0 ] || [ "$CRITICAL_SEVERITY" -gt 0 ]; then
            echo "::warning ::$WARNING_LINE"
            pnpm audit || true
            fi

            if [ "$CRITICAL_SEVERITY" -gt 0 ]; then
            echo "Critical vulnerabilities detected! Failing workflow."
            exit 1
            fi
        shell: bash      
      - name: Get Slack UserID
        if: failure()          
        id: get_slack_id
        uses: actions/github-script@v8
        env:
          SLACK_USER_MAP: ${{ secrets.SLACK_USERS_ID }}
        with:
          result-encoding: string
          script: |
            const map = JSON.parse(process.env.SLACK_USER_MAP);
            const slackUserId = map[context.actor];
            
            if (!slackUserId) {
              console.log(`No Slack mapping for ${context.actor}`);
              return '';
            }
            
            console.log(`Slack User ID for ${context.actor}: ${slackUserId}`);
            return slackUserId;


      - name: Post text to a Slack channel
        if: failure()               
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ steps.get_slack_id.outputs.result }}
            text: |
              ❌ Pnpm Audit Workflow failed
              Workflow: ${{ github.workflow }}
              Repo: ${{ github.repository }}
              Actor: ${{ github.actor }}